### ISSUE TITLE
MotB coven armor recipes

### ISSUE THREAD

**Issue by kevL** [kevL/TccScripts#20]
rows 1202..1206
ArmorBonus +
ArmorBonusVsRace +
Immunity Mind-affecting

Each of those 5 recipes specify an ArmorBonus that is 2 greater than the ArmorBonusVsRace(outsider). Unless they stack (which I doubt) it seems absurd to have an armor bonus (vs all) that is greater than an armor bonus vs anything specific ...

**Comment by vandervecken** [comment]
This is not a normal recipe - it's a recipe for an extremely rare item that is found in only one place, and only if you follow a very specific approach and it's very hard to do. These recipes are part of the story, and ought not to be touched. 
In general I'm not in favour of editing any recipes that use the feats Mold Spirit or Malleate Spirit, or make use of Mask of the Betrayer Essences - since they are specific to that expansion and have no application anywhere else.

**Comment by vandervecken** [comment]
To put more colour here: In order to claim an Eye of the Coven you need to:
a) choose to fight the Coven (an evil choice typically)
b) use Devour Spirit in the middle of the battle in such a way that the damage dealt to the Coven Hag is enough to kill her. Not easy.
c) since Devour Spirit has a cooldown of 5 minutes, in order to get more than one of these you have to somehow stall the fight for 5 minutes, and then do it again. And again. I did this. It's incredibly hard. It took me many tries and a lot of dirty tricks.

**Comment by kevL** [comment]
cool
